DROP TABLE IF EXISTS `WorkFavorites`;
DROP TABLE IF EXISTS `WorkStudents`;
DROP TABLE IF EXISTS `StudentTeachers`;
DROP TABLE IF EXISTS `ModerationItems`;
DROP TABLE IF EXISTS `Works`;
DROP TABLE IF EXISTS `Users`;
DROP TABLE IF EXISTS `__EFMigrationsHistory`;